# Курс GeekBrains  DataScience

## Тема “Вычисления с помощью Numpy”

__Задание 1__  

Импортируйте библиотеку Numpy и дайте ей псевдоним np.  
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [2]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 3, 1],
            [6, 8, 11, 10, 7]])

In [9]:
a[0].mean()

2.0

In [10]:
a[1].mean()

8.4

In [17]:
mean_a = []
mean_a.append([a[0].mean()])  
mean_a.append([a[1].mean()]) 
mean_a

[[2.0], [8.4]]

__Задание 2__  
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [18]:
a_centered = a - mean_a
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

__Задание 3__  
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [20]:
a_centered_sp = a_centered[0] * a_centered[1]
a_centered_sp / 4

array([ 0.6 , -0.  ,  0.65,  0.4 ,  0.35])

In [25]:
n = a.shape[1]

In [26]:
a_centered_sp / n - 4

array([-3.52, -4.  , -3.48, -3.68, -3.72])

__Задание 4**__  
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации


В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [27]:
np.cov(a.T)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

In [32]:
np.cov(a.transpose())

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

# Тема “Работа с данными в Pandas”

__Задание 1__  
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [33]:
import pandas as pd

In [46]:
authors = pd.DataFrame(columns = {'author_id', 'author_name'})
authors['author_id'] = [1, 2, 3]
authors['author_name'] = ['Тургенев', 'Чехов', 'Островский']
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [51]:
book = pd.DataFrame(columns = {'author_id', 'book_title', 'price'})
book['author_id'] = [1, 1, 1, 2, 2, 3, 3]
book['book_title'] = (
    ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
)
book['price'] = [450, 300, 350, 500, 450, 370, 290]
book

author_id  price            book_title
0          1    450           Отцы и дети
1          1    300                 Рудин
2          1    350     Дворянское гнездо
3          2    500      Толстый и тонкий
4          2    450       Дама с собачкой
5          3    370                 Гроза
6          3    290  Таланты и поклонники

__Задание 2__  
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [54]:
authors_price = authors.merge(book)
authors_price

author_id author_name  price            book_title
0          1    Тургенев    450           Отцы и дети
1          1    Тургенев    300                 Рудин
2          1    Тургенев    350     Дворянское гнездо
3          2       Чехов    500      Толстый и тонкий
4          2       Чехов    450       Дама с собачкой
5          3  Островский    370                 Гроза
6          3  Островский    290  Таланты и поклонники

__Задание 3__  
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [55]:
authors_price.sort_values(by='price',ascending = False).head(5)

author_id author_name  price         book_title
3          2       Чехов    500   Толстый и тонкий
0          1    Тургенев    450        Отцы и дети
4          2       Чехов    450    Дама с собачкой
5          3  Островский    370              Гроза
2          1    Тургенев    350  Дворянское гнездо

__Задание 4__  
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [61]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max','mean'])
authors_stat

min  max        mean
author_name                      
Островский   290  370  330.000000
Тургенев     300  450  366.666667
Чехов        450  500  475.000000

__Задание 5**__  
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:  
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].  
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.  
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [62]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name  price            book_title    cover
0          1    Тургенев    450           Отцы и дети  твердая
1          1    Тургенев    300                 Рудин   мягкая
2          1    Тургенев    350     Дворянское гнездо   мягкая
3          2       Чехов    500      Толстый и тонкий  твердая
4          2       Чехов    450       Дама с собачкой  твердая
5          3  Островский    370                 Гроза   мягкая
6          3  Островский    290  Таланты и поклонники   мягкая

In [79]:
book_info = authors_price.pivot_table(index='author_name', columns ='cover', aggfunc='sum', fill_value=0).reset_index()
book_info

author_name author_id          price        
cover                мягкая твердая мягкая твердая
0      Островский         6       0    660       0
1        Тургенев         2       1    650     450
2           Чехов         0       4      0     950

In [93]:
#book_info.to_csv('book_info.pkl')
np.save('book_info.npy', book_info)

In [94]:
#book_info2 = pd.read_csv('book_info.pkl')
book_info2 = np.load('book_info.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [95]:
book_info

author_name author_id          price        
cover                мягкая твердая мягкая твердая
0      Островский         6       0    660       0
1        Тургенев         2       1    650     450
2           Чехов         0       4      0     950

In [96]:
book_info2

Unnamed: 0 author_name author_id author_id.1   price  price.1
0      cover         NaN    мягкая     твердая  мягкая  твердая
1          0  Островский         6           0     660        0
2          1    Тургенев         2           1     650      450
3          2       Чехов         0           4       0      950

# Конец